#!/bin/bash
# Claude Code Wrapper Script with pseudo-TTY and file-based output

export HOME="${PHANTOM_CLAUDE_HOME:-${HOME:-/root}}"
export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"
export USER="${USER:-root}"
export TERM=xterm-256color
export IS_SANDBOX=1

# Disable Claude Code's internal cron so sessions launched through this
# wrapper rely on external cron instead.
export CLAUDE_CODE_DISABLE_CRON=1

# Use the repo-local settings.json (generated by the orchestrator).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SETTINGS_FILE="$SCRIPT_DIR/settings.json"
SETTINGS_ARGS=()
SETTINGS_CMD=""
if [ -f "$SETTINGS_FILE" ]; then
    SETTINGS_ARGS=(--settings "$SETTINGS_FILE")
    escaped_settings=$(printf '%s' "$SETTINGS_FILE" | sed "s/'/'\\\\''/g")
    SETTINGS_CMD=" --settings '$escaped_settings'"
else
    echo "WARN: settings file not found at $SETTINGS_FILE; using Claude default settings" >&2
fi

# Create a temp file for output
TMPFILE=$(mktemp)
trap "rm -f $TMPFILE" EXIT

# Build properly quoted command
QUOTED_ARGS=""
for arg in "$@"; do
    # Escape single quotes in the argument and wrap in single quotes
    escaped_arg=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
    QUOTED_ARGS="$QUOTED_ARGS '$escaped_arg'"
done

# Locate the claude binary (npm global install location varies by environment)
CLAUDE_BIN=""
for candidate in "$HOME/.local/bin/claude" "/root/.local/bin/claude" "/usr/local/bin/claude" "/usr/bin/claude" "$(which claude 2>/dev/null)"; do
    if [ -x "$candidate" ]; then
        CLAUDE_BIN="$candidate"
        break
    fi
done

if [ -z "$CLAUDE_BIN" ]; then
    echo "ERROR: claude binary not found. Tried: $HOME/.local/bin/claude, /root/.local/bin/claude, /usr/local/bin/claude, /usr/bin/claude" >&2
    exit 1
fi

# Run claude with script for pseudo-TTY (using the original binary).
# GNU util-linux script accepts `-c`; macOS/BSD script expects the command
# after the output file. Support both so local POCs do not silently skip Claude.
SCRIPT_STATUS=0
if script -q /dev/null -c "true" >/dev/null 2>&1; then
    script -q /dev/null -c "$CLAUDE_BIN$SETTINGS_CMD $QUOTED_ARGS" > "$TMPFILE" 2>&1
    SCRIPT_STATUS=$?
else
    script -q /dev/null "$CLAUDE_BIN" "${SETTINGS_ARGS[@]}" "$@" > "$TMPFILE" 2>&1
    SCRIPT_STATUS=$?
fi

# Clean and output the result (remove ANSI codes, OSC sequences, and control chars)
perl -pe 's/\r//g; s/\e\[[0-?]*[ -\/]*[@-~]//g; s/\e\][^\a]*(?:\a|\e\\)//g; s/\e[\(\)][A-Za-z0-9]//g; s/\e[78]//g; s/\e[ -\/]*[@-~]//g; s/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]//g' "$TMPFILE"
exit "$SCRIPT_STATUS"
